# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: NodePort
  ports:
  - port: {{default 80 .Values.httpPort}}
    nodePort: 30080
    targetPort: http
    protocol: TCP
    name: http
  - port: 30080
    targetPort: http
    protocol: TCP
    name: http
  - name: ssh
    nodePort: 30022
    port: 22
    protocol: TCP
    targetPort: ssh
  selector:
    app: gitlab
