stages:
  - test
  - build

lint-worker-dockerfile:
  image: willies/dockerfile_lint:a36b300_git.0
  stage: test
  script:
    - dockerfile_lint -f worker/Dockerfile

lint-result-dockerfile:
  image: willies/dockerfile_lint:a36b300_git.0
  stage: test
  script:
    - dockerfile_lint -f result/Dockerfile


build-worker-container:
  image: gitlab/dind
  stage: build
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
    - docker build worker/

build-result-container:
  image: gitlab/dind
  stage: build
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
    - ls -lah /root
    - cat /root/.docker/config.json
    - ls -lah /home/gitlab-runner/
    - whoami
    - sleep 120s
    - docker build -t willies/example-voting-app-result result/
    - docker push willies/example-voting-app-result
