stages:
  - test
  - build
  - deploy-dev
  - int-test

## testing section
lint-worker-dockerfile:
  image: willies/dockerfile_lint:a36b300_git.0
  stage: test
  script:
    - dockerfile_lint -f example-voting-app/vote//Dockerfile

lint-result-dockerfile:
  image: willies/dockerfile_lint:a36b300_git.0
  stage: test
  script:
    - dockerfile_lint -f example-voting-app/result/Dockerfile

### building section
build-worker-container:
  image: gitlab/dind
  stage: build
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
    - docker build -t willies/example-voting-app-vote:${CI_BUILD_REF:0:8} example-voting-app/vote/
    - docker push willies/example-voting-app-vote:${CI_BUILD_REF:0:8}

build-result-container:
  image: gitlab/dind
  stage: build
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
    - docker build -t willies/example-voting-app-result:${CI_BUILD_REF:0:8} example-voting-app/result/
    - docker push willies/example-voting-app-result:${CI_BUILD_REF:0:8}

### deploy to dev
deploy-result-container-to-dev:
  image: willies/helm:2.0.0-beta.2
  stage: deploy-dev
  environment: dev
  script:
    - helm upgrade result-app charts/example-voting-app/charts/result-app -i --set nodePort=30051,imageTag=${CI_BUILD_REF:0:8}

### integration test
integration-test:
  image: willies/phantomjs:6
  stage: int-test
  script:
    - export NS_UUID=$(uuidgen |cut -f1 -d-)
    - helm install --namespace=$NS_UUID charts/example-voting-app/ --set voting-app.imageTag=${CI_BUILD_REF:0:8},result-app.imageTag=${CI_BUILD_REF:0:8}
    - while ! curl -s -o /dev/null http://voting-app.$NS_UUID.svc; do echo "waiting for voting-app" && sleep 5; done
    - while ! curl -s -o /dev/null http://result-app.$NS_UUID.svc; do echo "waiting for result-app" && sleep 5; done
    - while ! pg_isready -h db.$NS_UUID.svc; do echo "waiting for postgres" && sleep 5; done
    - curl -sS -X POST --data "vote=b" http://voting-app.$NS_UUID.svc > /dev/null
    - sleep 5s
    - phantomjs example-voting-app/result/tests/render.js http://result-app.$NS_UUID.svc
    - sleep 180s
    - if ! phantomjs example-voting-app/result/tests/render.js http://result-app.$NS_UUID.svc | grep -q '1 vote'; then exit 1; fi
    - kubectl delete ns $NS_UUID
