stages:
  - test
  - build
  - deploy

### testing section
# lint-worker-dockerfile:
#   image: willies/dockerfile_lint:a36b300_git.0
#   stage: test
#   script:
#     - dockerfile_lint -f worker/Dockerfile

lint-result-dockerfile:
  image: willies/dockerfile_lint:a36b300_git.0
  stage: test
  script:
    - dockerfile_lint -f example-voting-app/result/Dockerfile

# ### building section
# build-worker-container:
#   image: gitlab/dind
#   stage: build
#   variables:
#     DOCKER_API_VERSION: "1.23"
#   script:
#     - docker build worker/

build-result-container:
  image: gitlab/dind
  stage: build
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
    - docker build -t willies/example-voting-app-result:${CI_BUILD_REF:0:8} example-voting-app/result/
    - docker push willies/example-voting-app-result:${CI_BUILD_REF:0:8}

### deploy section
deploy-result-container:
  image: willies/helm:2.0.0-beta.2
  stage: deploy
  environment: dev
  script:
    - helm upgrade result-app charts/example-voting-app/charts/result-app -i --set nodePort=30051,imageTag=${CI_BUILD_REF:0:8}
