# image: gitlab/dind

stages:
  - lint
  - build

lint-file:
  image: projectatomic/dockerfile-lint
  stage: lint
  script:
    - dockerfile_lint -f worker/Dockerfile

build-container:
  image: gitlab/dind
  stage: build
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
    - docker build worker/
