apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  labels:
    release: {{ .Release.Name | quote }}
    app: gitlab-runner
    heritage: {{.Release.Service | quote }}
data:
  config.toml: |-
    concurrent = 4
    [[runners]]
      name = "Kubernetes Runner"
      url = "http://gitlab:30080/ci"
      token = {{.Values.token | quote }}
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "infra"
        privileged = true
